number1 = input("Please enter a number between 1 and 10: ")
number2 = input("Please enter a second number between 1 and 10: ")
number3 = float(number1)
number4 = float(number2)
print("The product of " + number1 + " and " + number2 + " is " + str(number3 * number4))